### Start

In [ ]:
import requests
import json
import pandas as pd

In [ ]:
url = 'https://api.covid19api.com/'
data = requests.get(url)
data

<Response [200]>

### 0. All countries

In [79]:
url = 'https://api.covid19api.com/countries'
data = requests.get(url)
data

<Response [200]>

In [85]:
d = json.loads(data.content)
for c in d: print(c['Slug'])

denmark
greece
oman
poland
botswana
cambodia
tonga
cook-islands
kenya
holy-see-vatican-city-state
ireland
tunisia
us-minor-outlying-islands
jordan
montenegro
russia
estonia
new-zealand
saint-lucia
samoa
svalbard-and-jan-mayen-islands
tanzania
anguilla
guadeloupe
ecuador
gibraltar
mayotte
morocco
saint-pierre-and-miquelon
sweden
united-states
switzerland
united-arab-emirates
ethiopia
kyrgyzstan
puerto-rico
seychelles
bangladesh
central-african-republic
congo-kinshasa
norway
china
rwanda
saint-vincent-and-the-grenadines
philippines
indonesia
nigeria
american-samoa
germany
montserrat
mozambique
pakistan
saudi-arabia
tuvalu
chad
british-virgin-islands
egypt
sao-tome-and-principe
solomon-islands
haiti
iran
bouvet-island
croatia
bosnia-and-herzegovina
guinea
mauritius
mexico
libya
mali
iraq
cote-divoire
liberia
armenia
norfolk-island
british-indian-ocean-territory
moldova
kiribati
malaysia
venezuela
fiji
guyana
mongolia
belize
french-southern-territories
italy
ala-aland-islands
northern-mari

### 1. Country-cases

In [90]:
%%time

import time

start = '2022-11-01'
end = '2022-11-25'
asia_list = ['singapore', 'malaysia', 'vietnam', 'thailand', 'indonesia', 'taiwan', 'korea-south', 'korea-north']
df_list = []

for country in asia_list:
    url = f'https://api.covid19api.com/country/{country}/status/confirmed?from={start}T00:00:00Z&to={end}T00:00:00Z'
    data = requests.get(url)
    d = json.loads(data.content)
    df = pd.DataFrame(d)
    df_list.append(df)
    print(f'Completed: {country}')
    time.sleep(2)

Completed: singapore
Completed: malaysia
Completed: vietnam
Completed: thailand
Completed: indonesia
Completed: taiwan
Completed: korea-south
Completed: korea-north
CPU times: user 393 ms, sys: 26.5 ms, total: 419 ms
Wall time: 22.6 s


In [97]:
df = pd.concat(df_list).groupby(['Country', 'Lat', 'Lon', 'Date']).sum()
df = df.reset_index()
df = df.rename({"Lat":"lat", "Lon":"lon"}, axis=1)

In [105]:
df.dtypes

Country    object
Lat        object
Lon        object
Date       object
Cases       int64
dtype: object

In [76]:
start = '2022-11-01'
end = '2022-11-25'
country = 'singapore'
url = f'https://api.covid19api.com/country/singapore/status/confirmed?from={start}T00:00:00Z&to={end}T00:00:00Z'
# url = 'https://api.covid19api.com/country/south-africa/status/confirmed?from=2020-03-01T00:00:00Z&to=2020-04-01T00:00:00Z'
data = requests.get(url)
data

<Response [200]>

In [77]:
d = json.loads(data.content)
pd.DataFrame(d)

Country CountryCode Province City CityCode   Lat     Lon    Cases  \
0   Singapore          SG                         1.35  103.82  2108024   
1   Singapore          SG                         1.35  103.82  2112110   
2   Singapore          SG                         1.35  103.82  2115621   
3   Singapore          SG                         1.35  103.82  2118749   
4   Singapore          SG                         1.35  103.82  2121435   
5   Singapore          SG                         1.35  103.82  2123328   
6   Singapore          SG                         1.35  103.82  2125004   
7   Singapore          SG                         1.35  103.82  2128572   
8   Singapore          SG                         1.35  103.82  2131554   
9   Singapore          SG                         1.35  103.82  2134319   
10  Singapore          SG                         1.35  103.82  2136658   
11  Singapore          SG                         1.35  103.82  2138598   
12  Singapore          SG                         1.35  103.82  2140099   
13  Singapore          SG                         1.35  103.82  2141411   
14  Singapore          SG                         1.35  103.82  2144522   
15  Singapore          SG                         1.35  103.82  2146706   
16  Singapore          SG                         1.35  103.82  2148794   
17  Singapore          SG                         1.35  103.82  2150702   
18  Singapore          SG                         1.35  103.82  2152368   
19  Singapore          SG                         1.35  103.82  2153535   
20  Singapore          SG                         1.35  103.82  2154633   
21  Singapore          SG                         1.35  103.82  2157021   
22  Singapore          SG                         1.35  103.82  2158709   
23  Singapore          SG                         1.35  103.82  2160324   
24  Singapore          SG                         1.35  103.82  2161673   

       Status                  Date  
0   confirmed  2022-11-01T00:00:00Z  
1   confirmed  2022-11-02T00:00:00Z  
2   confirmed  2022-11-03T00:00:00Z  
3   confirmed  2022-11-04T00:00:00Z  
4   confirmed  2022-11-05T00:00:00Z  
5   confirmed  2022-11-06T00:00:00Z  
6   confirmed  2022-11-07T00:00:00Z  
7   confirmed  2022-11-08T00:00:00Z  
8   confirmed  2022-11-09T00:00:00Z  
9   confirmed  2022-11-10T00:00:00Z  
10  confirmed  2022-11-11T00:00:00Z  
11  confirmed  2022-11-12T00:00:00Z  
12  confirmed  2022-11-13T00:00:00Z  
13  confirmed  2022-11-14T00:00:00Z  
14  confirmed  2022-11-15T00:00:00Z  
15  confirmed  2022-11-16T00:00:00Z  
16  confirmed  2022-11-17T00:00:00Z  
17  confirmed  2022-11-18T00:00:00Z  
18  confirmed  2022-11-19T00:00:00Z  
19  confirmed  2022-11-20T00:00:00Z  
20  confirmed  2022-11-21T00:00:00Z  
21  confirmed  2022-11-22T00:00:00Z  
22  confirmed  2022-11-23T00:00:00Z  
23  confirmed  2022-11-24T00:00:00Z  
24  confirmed  2022-11-25T00:00:00Z

In [118]:
day_to_filter = 5
# day_to_filter = df[df.Date >= (datetime.datetime.today() - datetime.timedelta(days=30)) + datetime.timedelta(days=day_to_filter)]
# (datetime.datetime.today() - datetime.timedelta(days=30)) + datetime.timedelta(days=day_to_filter)
# df['Date'] == (datetime.datetime.today() - datetime.timedelta(days=30)) + datetime.timedelta(days=day_to_filter)
df['Date'] = df['Date'].str[:10]

In [122]:
df[df['Date'] == ((datetime.datetime.today() - datetime.timedelta(days=30)) + datetime.timedelta(days=day_to_filter)).strftime('%Y-%m-%d')]

Country    Lat     Lon        Date     Cases
1                    Indonesia  -0.79  113.92  2022-11-02   6502659
26               Korea (North)  40.34  127.51  2022-11-02         1
51               Korea (South)  35.91  127.77  2022-11-02  25717277
76                    Malaysia   4.21  101.98  2022-11-02   4909846
101                  Singapore   1.35  103.82  2022-11-02   2112110
126  Taiwan, Republic of China   23.7  120.96  2022-11-02   7780125
151                   Thailand  15.87  100.99  2022-11-02   4692448
176                   Viet Nam  14.06  108.28  2022-11-02  11504091

### World WIP

In [27]:
start = '2022-11-01'
end = '2022-11-25'
url = f'https://api.covid19api.com/world?from={start}T00:00:00Z&to={end}T00:00:00Z'
world_wip = requests.get(url)
world_wip

<Response [200]>

In [70]:
d = json.loads(world_wip.content)
df = pd.DataFrame(d)


In [71]:
d = json.loads(world_wip.content)
df = pd.DataFrame(d)
df['Date'] = df['Date'].str[:10]
df['Date'] = pd.to_datetime(df['Date'])
df

NewConfirmed  TotalConfirmed  NewDeaths  TotalDeaths  NewRecovered  \
0         469555       635333213       2587      6611892             0   
1         783647       638547623       1863      6621982             0   
2         665081       639226054       1981      6623992             0   
3         370203       629419996       2638      6587381             0   
4         416540       631834247       1166      6597158             0   
5         557222       634863658       2160      6609171             0   
6         469555       635333213       2587      6611892             0   
7         469555       635333213       2587      6611892             0   
8         469555       635333213       2587      6611892             0   
9         185964       631098197        480      6594885             0   
10        880607       632714854       4830      6601988             0   
11        350627       633941181       1530      6605899             0   
12        416540       631834247       1166      6597158             0   
13        359563       634299878       1415      6607335             0   
14        557672       637231671       1821      6618006             0   
15        540472       637777994       2265      6620119             0   
16        370203       629419996       2638      6587381             0   
17        467066       630296209       2880      6592027             0   
18        422038       630719214       1852      6593879             0   
19        416540       631834247       1166      6597158             0   
20        218880       633407395        474      6604050             0   
21        182063       633589458        437      6604369             0   
22        330641       636673999       1052      6616185             0   
23        298351       629049904       1112      6584743             0   
24        193019       630912233        526      6594405             0   
25        320976       631419173       1125      6596010             0   

    TotalRecovered       Date  
0                0 2022-11-21  
1                0 2022-11-25  
2                0 2022-11-26  
3                0 2022-11-02  
4                0 2022-11-11  
5                0 2022-11-17  
6                0 2022-11-18  
7                0 2022-11-19  
8                0 2022-11-20  
9                0 2022-11-07  
10               0 2022-11-12  
11               0 2022-11-15  
12               0 2022-11-10  
13               0 2022-11-16  
14               0 2022-11-23  
15               0 2022-11-24  
16               0 2022-11-03  
17               0 2022-11-04  
18               0 2022-11-05  
19               0 2022-11-09  
20               0 2022-11-13  
21               0 2022-11-14  
22               0 2022-11-22  
23               0 2022-11-01  
24               0 2022-11-06  
25               0 2022-11-08

In [75]:
start = (datetime.datetime.today() - datetime.timedelta(days=30))
day_to_filter = start + datetime.timedelta(days=15)
df['Date'] >= day_to_filter

0      True
1      True
2      True
3     False
4     False
5      True
6      True
7      True
8      True
9     False
10    False
11     True
12    False
13     True
14     True
15     True
16    False
17    False
18    False
19    False
20     True
21     True
22     True
23    False
24    False
25    False
Name: Date, dtype: bool

In [ ]:
df[['NewConfirmed', 'TotalConfirmed']]

NewConfirmed  TotalConfirmed
0         469555       635333213
1         783647       638547623
2         665081       639226054
3         370203       629419996
4         416540       631834247
5         557222       634863658
6         469555       635333213
7         469555       635333213
8         469555       635333213
9         185964       631098197
10        880607       632714854
11        350627       633941181
12        416540       631834247
13        359563       634299878
14        557672       637231671
15        540472       637777994
16        370203       629419996
17        467066       630296209
18        422038       630719214
19        416540       631834247
20        218880       633407395
21        182063       633589458
22        330641       636673999
23        298351       629049904
24        193019       630912233
25        320976       631419173

In [51]:
np.histogram(df['NewConfirmed'], bins=24)

(array([3, 1, 0, 1, 1, 2, 3, 0, 4, 5, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1]),
 array([182063., 211169., 240275., 269381., 298487., 327593., 356699.,
        385805., 414911., 444017., 473123., 502229., 531335., 560441.,
        589547., 618653., 647759., 676865., 705971., 735077., 764183.,
        793289., 822395., 851501., 880607.]))

In [49]:
import datetime
import numpy as np

np.histogram(df['NewConfirmed'], bins=24, range=(0,24))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]),
 array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]))

In [38]:
datetime.datetime.today().strftime("%Y-%m-%d")

'2022-11-27'

In [41]:
(datetime.datetime.today() - datetime.timedelta(days=30)).strftime("%Y-%m-%d")

'2022-10-28'